sudo: false
language: node_js
node_js: '10'

cache: yarn

notifications:
  email: false

install: yarn install --frozen-lockfile --non-interactive

script:
  - yarn lint
  - yarn test

branches:
  only:
    - master
